ALL: variant8

CFILE = list_direct_linked_linear_list.c list_queue.c list_init.c
HFILE = list_direct_linked_linear_list.h list_queue.h list_init.h



variant4: ${CFILE} variant_4.c ${HFILE}
	gcc ${CFILE} variant_4.c -o variant_4 -g

variant8: ${CFILE} variant_8.c ${HFILE}
	gcc ${CFILE} variant_8.c -o variant_8 -g


