#ifndef _H_VARIANT_H_
#define _H_VARIANT_H_
void Variant1(); 
void Variant2();
void Variant3();
void Variant4();
void Variant5();
void Variant6();
void Variant7();
void Variant8();
void Variant9();
void Variant10();
void Variant11();
void Variant12();
void Variant13();
void Variant15();
void Variant15();
void Variant16();
void Variant17();
void Variant18();
void Variant19();
void Variant20();
void Variant21();
void Variant22();
void Variant23();
void Variant24();
void Variant25();
void Variant26();

#endif
