ALL:list


list: ../input_key.c ../list_init.c ../list_sort.c ../variant.c ../list_print.c ../list_free.c directed_linear_list_test.c    ../variant.h ../list.h
	gcc ../input_key.c ../list_init.c ../list_sort.c ../list_print.c ../variant.c ../list_free.c directed_linear_list_test.c -o list_variant -g
